### ISSUE TITLE
export `isValidElement`?

### ISSUE THREAD

**Issue by ljharb** [facebook/prop-types#1]
Could there be an entry point for `isValidElement`? I'd like to use it without depending on React :-)

**Comment by sebmarkbage** [comment]
Wut? For production? I thought the point was so that when you're doing non-React related stuff you can still use propTypes. If you're testing for elements it seems like you can just use the React package. It is designed to be lightweight anyway and if it is not because of bad DCE tooling we can solve it the same as lodash.

I came on to actually suggest the opposite. We shouldn't have the factory thing and instead inline it in the DEV conditional. So that it gets removed completely in production.

**Comment by ljharb** [comment]
It's fine if you want the default to remove things in production; but yes, sometimes I might want to use it in production to make a prop that takes an element-returning thunk, and validate in the render path that it's a valid element.

**Comment by ljharb** [comment]
@sebmarkbage is there any chance in `isValidElement` being exposed anywhere? #3 is still ready to go :-)

**Comment by sebmarkbage** [comment]
If you're in a context where you assume that you've already created a `ReactElement` then you've probably already loaded `React` anyway so seems like the dependency shouldn't be an issue, right?

Would your use case be satisfied by `PropTypes.checkPropTypes(PropTypes.element, yourReturnedElement, 'element', 'MyComponent');`? Assuming a production-enabled version of `PropTypes`.

I really don't think that additional APIs outside of validators and `checkPropTypes` belong in this package. Neither does `isArray` or `isError` or similar.

**Comment by ljharb** [comment]
The goal isn't "to not have to load React", it's to not semver-depend on breaking changes in React that aren't "the meaning of what a valid element is", which is most of them.

I agree this package isn't the right place for it; ideally it'd live in its own distinct package so that React itself, as well as this package, could depend on it instead of copypastaing the code for it.

**Comment by ljharb** [comment]
This now exists as `isElement` in `react-is`.
