### ISSUE TITLE
Proposal to destructure prop-types on import statement as a standard 

### ISSUE THREAD

**Issue by yasuf** [facebook/prop-types#150]
Hello React community,

I'd  like to propose the following when importing `prop-types` to components

Instead of doing i.e.
```javascript
import PropTypes from 'prop-types'

class MyComponent extends Component {
  static propTypes = {
    fetchData: PropTypes.func
  }
}
```
We could have the more concise option with destructuring
```javascript
import { func } from 'prop-types'

class MyComponent extends Component {
  static propTypes = {
    fetchData: func
  }
}
```

Small improvement that makes it easier to see the type of each prop on a component at a glance.

Is there any reason this hasn't been chosen as the standard?

**Comment by ljharb** [comment]
You can already do this, since babel treats named import syntax as destructuring when importing a CJS module.

I'm sure that when node ships modules unflagged, this module will ship with an `.mjs` file that allows for the same syntax natively.

(That said, in this case I personally find the destructured version less readable, and we enforce that people use the full "PropTypes.blah" in airbnb's codebase)
