### ISSUE TITLE
add deep object merging for defaultProps

### ISSUE THREAD

**Issue by SilencerWeb** [facebook/prop-types#193]
What about deep object merging for defaultProps?

For example, I have such code:
```js
TextField.propTypes = {
  icon: PropTypes.shape({
    svg: PropTypes.any.isRequired,
    position: PropTypes.string,
    rotation: PropTypes.number,
  }),
};

TextField.defaultProps = {
  icon: {
    position: 'right',
    rotation: 0,
  },
};
```

now, if render component like 
```js
<TextField icon={ { svg: 'something' } }/>;
```

I will receive such props: 
```js
icon: {
  svg: 'something'
}
```
but it would be better if i receive
```js
icon: {
  svg: 'something',
  position: 'right',
  rotation: 0,
},
```

**Comment by ljharb** [comment]
There’s nothing in the language that does that deep merging for you, and it wouldn’t make sense for react to choose which deep merging algorithm to use. You can do this yourself inside your Component.

**Comment by ljharb** [comment]
This is both answered, and would be part of react itself, not this library.

**Comment by Yzrsah** [comment]
@ljharb you cannot do it inside your component.

Because you are not supposed to modify props in the constructor.

Therefore all the code must be disrupted and stateless components must be converted into stateful component for no other reason than to support a simple default property merge like in the example shown above.

There's actually no way to fix it and nothing you can do "Yourself", short of relying on undefined behavior. You can convert to a class and then assign to props before calling super(props). But even that is not enough because you're not supposed to do that. You need to add state.

It makes simple default properties that are nested by 1 level very unusable. You need to avoid that altogether.

**Comment by Yzrsah** [comment]
@ljharb you cannot do it inside your component.

Because you are not supposed to modify props in the constructor.

Therefore all the code must be disrupted and stateless components must be converted into stateful component for no other reason than to support a simple default property merge like in the example shown above.

There's actually no way to fix it and nothing you can do "Yourself", short of relying on undefined behavior. You can convert to a class and then assign to props before calling super(props). But even that is not enough because you're not supposed to do that. You need to add state.

It makes simple default properties that are nested by 1 level very unusable, so that you need to avoid that altogether.

**Comment by Yzrsah** [comment]
@ljharb you cannot do it inside your component.

Because you are not supposed to modify props in the constructor.

Therefore all the code must be disrupted and stateless components must be converted into stateful component for no other reason than to support a simple default property merge like in the example shown above.

There's actually no way to fix it and nothing you can do "Yourself", short of relying on undefined behavior. You can convert to a class and then assign to props before calling super(props). But even that is not enough because you're not supposed to do that. You need to add state.

It makes the use of simple default properties that are nested by 1 level very unusable, so that you need to avoid using that completely. And that's a bad thing to avoid because it's quite useful and commonly needed.
