### ISSUE TITLE
PropTypes.oneOf warning does not include expected types

### ISSUE THREAD

**Issue by aweary** [facebook/prop-types#9]
Original issue: https://github.com/facebook/react/issues/1919

**Comment by reznord** [comment]
@aweary Is that the reason why CRA doesn't warn if we do not include PropTypes in the application. But any reason why PropTypes is removed from React Core?

**Comment by jackyho112** [comment]
![screen shot 2017-04-14 at 12 19 18 am](https://cloud.githubusercontent.com/assets/25375401/25036339/1502d53e-20a8-11e7-8885-1bba70ad8023.png)

Looks like the warning message is still the same one that doesn't let the user know `oneOfType` should be used instead if the user is misusing `oneOf` by passing in `checkType` functions. 

All attempts to solve the problem as referenced in the discussion aimed to solve this potential misunderstanding by trying to identify this specific misuse and if identified, display a warning message to direct the user to use `oneOfType` instead. 

Is that what we are going with to solve this issue? May I give this one a go?

**Comment by hanumanthan** [comment]
@aweary Provided a warn in [PR 36](https://github.com/reactjs/prop-types/pull/36).

**Comment by ljharb** [comment]
If I want a prop to literally be a specific function, I have to be able to pass a function into oneOf.

**Comment by oliviertassinari** [comment]
- I believe the issue description is inaccurate. It's about `PropTypes.oneOfType` output that is hard to make actionable.
```jsx
  value: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.number,
    PropTypes.arrayOf(PropTypes.oneOfType([PropTypes.string, PropTypes.number])),
  ]),
```
![capture d ecran 2018-03-30 a 12 32 18](https://user-images.githubusercontent.com/3165635/38135068-699fcb7e-3416-11e8-881d-04d63ab8bcaf.png)

- `PropTypes.oneOf` output is great, for instance:
```js
color: PropTypes.oneOf(['default', 'inherit', 'primary', 'secondary']),
```
![capture d ecran 2018-03-30 a 12 29 28](https://user-images.githubusercontent.com/3165635/38135010-16bedf76-3416-11e8-9341-224ebc7480fb.png)

**Comment by joshalling** [comment]
I have been looking into supplying the expected types with a oneOfType warning. See PR #198 

However, I noticed that my solution does not account for using non-primitive types like `shape` or `exact` within `oneOfType`. It looks like that will be a much bigger project that will also involve writing more tests. 

My idea is to pass the expected types within the `PropTypeError`'s that are sent to the `createUnionTypeChecker` so that they are accessible within the scope of that function. That being said, a change like this has a big impact on the package as a whole as it would affect all `PropTypeError`'s moving forward.

I would love to tackle this if people are interested. However, I don't want to get really deep into this if it has no chance of being merged due to the overall effect it would have on the package, or if the community just doesn't see a need for it.

Thoughts?
