### ISSUE TITLE
Remove weird code

### ISSUE THREAD

**Issue by rumkin** [facebook/prop-types#94]
Just read sources and was surprised. About [this line](https://github.com/facebook/prop-types/blob/master/factoryWithThrowingShims.js#L18) of code. What does it protect it's code from?

```javascript
    if (secret === ReactPropTypesSecret) {
      // It is still safe when called from React.
      return;
    }
    // Prevent code from execution...
```

**Comment by ljharb** [comment]
It prevents propTypes from being called by anyone but React itself.

**Comment by rumkin** [comment]
@ljharb I see. And what's the goal?

**Comment by ljharb** [comment]
@rumkin to make it safe for minified React not to include propTypes in production

**Comment by rumkin** [comment]
@ljharb Is it instruction for builder?

**Comment by ljharb** [comment]
@rumkin i'm not sure what you're asking. The "secret" restriction was put up to ensure that nobody would be able to successfully use PropTypes in production outside of React calling `.propTypes` - that way, React is able to use their build process to strip out PropTypes altogether, safely (since in production, React doesn't exercise .propTypes).

**Comment by rumkin** [comment]
Why does PropTypes could not be used by others? Does it have some sensitive state? I can't understand this restriction.

**Comment by uniphil** [comment]
Because it would crash your app.

As @ljharb just wrote,

> that way, React is able to use their build process to strip out PropTypes altogether,

@rumkin there is some background in the readme: https://github.com/facebook/prop-types/blob/master/README.md#difference-from-reactproptypes-dont-call-validator-functions

You can't call PropTypes directly because they are removed from your production build. Your app would crash at runtime, and it would probably be hard to track down.

Stripping PropTypes in the production build is desirable for:

- Smaller app bundle, for faster loading and evaulation
- Faster production app, since the checks are skipped

If you must call them manually, the readme here already provides a solution:

> If you absolutely need to trigger the validation manually, call PropTypes.checkPropTypes(). Unlike the validators themselves, this function is safe to call in production, as it will be replaced by an empty function:
>
> ```js
> // Works with standalone PropTypes
> PropTypes.checkPropTypes(MyComponent.propTypes, props, 'prop', 'MyComponent');
> ```

**Comment by rumkin** [comment]
I thought that React itself should to decide when to call PropTypes and when not. And not PropTypes with strange hacks like that.

**Comment by ljharb** [comment]
This seems answered.
